<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>

	<!-- References -->
	<PropertyGroup Condition="'$(ApogeanMawPackedQA)' == 'true'">
		<DefineConstants>$(DefineConstants);APOGEAN_MAW_PACKED_QA</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		
	</ItemGroup>

</Project>
