using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace apogean.Content.Tiles
{
	/// <summary>
	/// Shared contract for permanent Campus materials. Each concrete type owns a complete
	/// 288x270 native auto-framed terrain sheet; structures use silhouette, trim, floor, glazing, and beams deliberately.
	/// </summary>
	public abstract class ProtectedCorporateTile : ModTile
	{
		protected abstract Color MapColor { get; }
		protected abstract int TileDust { get; }
		protected virtual bool BlocksLight => true;
		protected virtual bool IsGlass => false;

		public override void SetStaticDefaults()
		{
			Main.tileSolid[Type] = true;
			Main.tileBlockLight[Type] = BlocksLight;
			Main.tileNoSunLight[Type] = !IsGlass;
			Main.tileNoAttach[Type] = true;
			TileID.Sets.ChecksForMerge[Type] = true;
			MineResist = 100f;
			MinPick = 9999;
			DustType = TileDust;
			AddMapEntry(MapColor);
		}

		public override bool CanExplode(int i, int j) => false;
		public override bool CanKillTile(int i, int j, ref bool blockDamaged) => false;
	}

	public abstract class KesslerMaterial : ProtectedCorporateTile
	{
		protected override Color MapColor => new(76, 69, 64);
		protected override int TileDust => DustID.Titanium;
	}

	public abstract class HelixMaterial : ProtectedCorporateTile
	{
		protected override Color MapColor => new(166, 170, 158);
		protected override int TileDust => DustID.SilverCoin;
	}

	public abstract class SentrixMaterial : ProtectedCorporateTile
	{
		protected override Color MapColor => new(31, 61, 78);
		protected override int TileDust => DustID.Electric;
	}

	public sealed class KesslerBlock : KesslerMaterial { }
	public sealed class KesslerTrim : KesslerMaterial { }
	public sealed class KesslerFloor : KesslerMaterial { }
	public sealed class KesslerGlass : KesslerMaterial { protected override bool BlocksLight => false; protected override bool IsGlass => true; }
	public sealed class KesslerBeam : KesslerMaterial { }

	public sealed class HelixBlock : HelixMaterial { }
	public sealed class HelixTrim : HelixMaterial { }
	public sealed class HelixFloor : HelixMaterial { }
	public sealed class HelixGlass : HelixMaterial { protected override bool BlocksLight => false; protected override bool IsGlass => true; }
	public sealed class HelixBeam : HelixMaterial { }

	public sealed class SentrixBlock : SentrixMaterial { }
	public sealed class SentrixTrim : SentrixMaterial { }
	public sealed class SentrixFloor : SentrixMaterial { }
	public sealed class SentrixGlass : SentrixMaterial { protected override bool BlocksLight => false; protected override bool IsGlass => true; }
	public sealed class SentrixBeam : SentrixMaterial { }

	// Save compatibility for worlds generated by the earlier Campus blockout.
	public sealed class KesslerPlating : KesslerMaterial { }
	public sealed class HelixContainmentPanel : HelixMaterial { }
	public sealed class SentrixPanel : SentrixMaterial { }

	/// <summary>Mineable environmental shell for abandoned sites; curated salvage comes later.</summary>
	public abstract class RuinStructureTile : ModTile
	{
		protected abstract Color MapColor { get; }
		protected abstract int TileDust { get; }

		public override void SetStaticDefaults()
		{
			Main.tileSolid[Type] = true;
			Main.tileBlockLight[Type] = true;
			TileID.Sets.ChecksForMerge[Type] = true;
			MineResist = 1.4f;
			DustType = TileDust;
			AddMapEntry(MapColor);
		}
	}

	public sealed class KesslerRuinBlock : RuinStructureTile { protected override Color MapColor => new(92, 69, 58); protected override int TileDust => DustID.Iron; }
	public sealed class HelixRuinBlock : RuinStructureTile { protected override Color MapColor => new(151, 158, 148); protected override int TileDust => DustID.SilverCoin; }
	public sealed class SentrixRuinBlock : RuinStructureTile { protected override Color MapColor => new(39, 58, 69); protected override int TileDust => DustID.Electric; }
	public sealed class PrewarConcrete : RuinStructureTile { protected override Color MapColor => new(104, 96, 82); protected override int TileDust => DustID.Stone; }
	public sealed class MawResearchBlock : RuinStructureTile { protected override Color MapColor => new(86, 73, 48); protected override int TileDust => DustID.AmberBolt; }
}
